<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('categories')->insert([
            [
                'category_id' => 1,
                'category_uniqueid' => '46105664.69159548',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2022-11-11 12:05:55',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'project',
                'category_slug' => '1-seo',
            ],
            [
                'category_id' => 2,
                'category_uniqueid' => '07480753.29925123',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'client',
                'category_slug' => '2-default',
            ],
            [
                'category_id' => 3,
                'category_uniqueid' => '27183358.46141427',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'lead',
                'category_slug' => '3-default',
            ],
            [
                'category_id' => 4,
                'category_uniqueid' => '49157065.07361046',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'invoice',
                'category_slug' => '4-default',
            ],
            [
                'category_id' => 5,
                'category_uniqueid' => '89334039.24587060',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'estimate',
                'category_slug' => '5-default',
            ],
            [
                'category_id' => 6,
                'category_uniqueid' => '54933186.00904754',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'contract',
                'category_slug' => '6-default',
            ],
            [
                'category_id' => 7,
                'category_uniqueid' => '39724217.95906825',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'expense',
                'category_slug' => '7-default',
            ],
            [
                'category_id' => 8,
                'category_uniqueid' => '60361477.14086916',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'item',
                'category_slug' => '8-default',
            ],
            [
                'category_id' => 9,
                'category_uniqueid' => '89350153.04490019',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Support',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'ticket',
                'category_slug' => '9-support',
            ],
            [
                'category_id' => 10,
                'category_uniqueid' => '54399642.58528154',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Frequently Asked Questions',
                'category_description' => 'Answers to some of the most frequently asked questions',
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-call-out',
                'category_type' => 'knowledgebase',
                'category_slug' => '10-frequently-asked-questions',
            ],
            [
                'category_id' => 11,
                'category_uniqueid' => '29441850.71624788',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'proposal',
                'category_slug' => '11-proposal',
            ],
            [
                'category_id' => 60,
                'category_uniqueid' => '69798397.34117621',
                'category_created' => null,
                'category_updated' => null,
                'category_creatorid' => 0,
                'category_name' => 'Default',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-docs',
                'category_type' => 'subscription',
                'category_slug' => 'subscription',
            ],
            [
                'category_id' => 21,
                'category_uniqueid' => '46775500.74485788',
                'category_created' => '2020-09-02 15:41:04',
                'category_updated' => '2020-01-01 00:00:00',
                'category_creatorid' => 0,
                'category_name' => 'Uncategorised',
                'category_description' => null,
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-folder',
                'category_type' => 'milestones',
                'category_slug' => '1-uncategorised',
            ],
            [
                'category_id' => -1,
                'category_uniqueid' => '00265030.07496227',
                'category_created' => '2024-03-09 15:08:50',
                'category_updated' => '2024-03-09 15:08:50',
                'category_creatorid' => 0,
                'category_name' => 'General',
                'category_description' => 'General canned responses',
                'category_system_default' => 'yes',
                'category_visibility' => 'everyone',
                'category_icon' => 'sl-icon-docs',
                'category_type' => 'canned',
                'category_slug' => '',
            ],
        ]);
    }
}
