<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('roles')->insert([
            [
                'role_id' => 1,
                'role_created' => '2018-09-07 14:49:41',
                'role_updated' => '2018-09-07 14:49:41',
                'role_system' => 'yes',
                'role_type' => 'team',
                'role_name' => 'Administrator',
                'role_clients' => 3,
                'role_contacts' => 4,
                'role_contracts' => 3,
                'role_invoices' => 3,
                'role_estimates' => 3,
                'role_proposals' => 4,
                'role_payments' => 3,
                'role_items' => 3,
                'role_tasks' => 3,
                'role_tasks_scope' => 'global',
                'role_projects' => 3,
                'role_projects_scope' => 'global',
                'role_projects_billing' => '2',
                'role_leads' => 3,
                'role_leads_scope' => 'global',
                'role_expenses' => 3,
                'role_expenses_scope' => 'global',
                'role_timesheets' => 3,
                'role_timesheets_scope' => 'global',
                'role_team' => 3,
                'role_team_scope' => 'global',
                'role_tickets' => 3,
                'role_knowledgebase' => 3,
                'role_manage_knowledgebase_categories' => 'yes',
                'role_assign_projects' => 'yes',
                'role_assign_leads' => 'yes',
                'role_assign_tasks' => 'yes',
                'role_set_project_permissions' => 'yes',
                'role_subscriptions' => '3',
                'role_templates_projects' => '3',
                'role_templates_contracts' => '3',
                'role_templates_proposals' => '3',
                'role_content_import' => 'yes',
                'role_content_export' => 'yes',
                'role_module_cs_affiliate' => '3',
                'role_homepage' => 'dashboard',
                'role_messages' => 'yes',
                'role_reports' => 'yes',
                'role_canned' => 'yes',
                'role_canned_scope' => 'global',
                'role_workorders' => 3,
                'role_proforma_invoices' => 3
            ],
            [
                'role_id' => 3,
                'role_created' => '2018-09-07 14:49:41',
                'role_updated' => '2024-03-24 16:52:57',
                'role_system' => 'no',
                'role_type' => 'team',
                'role_name' => 'Staff',
                'role_clients' => 1,
                'role_contacts' => 1,
                'role_contracts' => 0,
                'role_invoices' => 0,
                'role_estimates' => 0,
                'role_proposals' => 3,
                'role_payments' => 0,
                'role_items' => 0,
                'role_tasks' => 3,
                'role_tasks_scope' => 'own',
                'role_projects' => 1,
                'role_projects_scope' => 'own',
                'role_projects_billing' => '0',
                'role_leads' => 3,
                'role_leads_scope' => 'own',
                'role_expenses' => 3,
                'role_expenses_scope' => 'own',
                'role_timesheets' => 2,
                'role_timesheets_scope' => 'own',
                'role_team' => 1,
                'role_team_scope' => 'global',
                'role_tickets' => 3,
                'role_knowledgebase' => 1,
                'role_manage_knowledgebase_categories' => 'no',
                'role_assign_projects' => 'no',
                'role_assign_leads' => 'no',
                'role_assign_tasks' => 'no',
                'role_set_project_permissions' => 'no',
                'role_subscriptions' => 'no',
                'role_templates_projects' => 'no',
                'role_templates_contracts' => 'no',
                'role_templates_proposals' => 'no',
                'role_content_import' => 'no',
                'role_content_export' => 'no',
                'role_module_cs_affiliate' => '3',
                'role_homepage' => 'dashboard',
                'role_messages' => 'yes',
                'role_reports' => 'no',
                'role_canned' => 'no',
                'role_canned_scope' => 'global',
                'role_workorders' => 3,
                'role_proforma_invoices' => 3
            ],
            [
                'role_id' => 2,
                'role_created' => '2018-09-07 14:49:41',
                'role_updated' => '2018-09-07 14:49:41',
                'role_system' => 'yes',
                'role_type' => 'client',
                'role_name' => 'Client',
                'role_clients' => 0,
                'role_contacts' => 3,
                'role_contracts' => 1,
                'role_invoices' => 1,
                'role_estimates' => 1,
                'role_proposals' => 0,
                'role_payments' => 1,
                'role_items' => 0,
                'role_tasks' => 1,
                'role_tasks_scope' => 'own',
                'role_projects' => 1,
                'role_projects_scope' => 'own',
                'role_projects_billing' => '0',
                'role_leads' => 0,
                'role_leads_scope' => 'own',
                'role_expenses' => 0,
                'role_expenses_scope' => 'own',
                'role_timesheets' => 1,
                'role_timesheets_scope' => 'own',
                'role_team' => 1,
                'role_team_scope' => 'global',
                'role_tickets' => 2,
                'role_knowledgebase' => 1,
                'role_manage_knowledgebase_categories' => 'no',
                'role_assign_projects' => 'no',
                'role_assign_leads' => 'no',
                'role_assign_tasks' => 'no',
                'role_set_project_permissions' => 'no',
                'role_subscriptions' => '1',
                'role_templates_projects' => '0',
                'role_templates_contracts' => '0',
                'role_templates_proposals' => '0',
                'role_content_import' => 'no',
                'role_content_export' => 'no',
                'role_module_cs_affiliate' => '3',
                'role_homepage' => 'dashboard',
                'role_messages' => 'yes',
                'role_reports' => 'no',
                'role_canned' => 'no',
                'role_canned_scope' => 'own',
                'role_workorders' => 0,
                'role_proforma_invoices' => 0
            ],
            [
                'role_id' => 4,
                'role_created' => '2018-09-07 14:49:41',
                'role_updated' => '2018-09-07 14:49:41',
                'role_system' => 'yes',
                'role_type' => 'team',
                'role_name' => 'Lead Associates',
                'role_clients' => 0,
                'role_contacts' => 0,
                'role_contracts' => 0,
                'role_invoices' => 0,
                'role_estimates' => 0,
                'role_proposals' => 0,
                'role_payments' => 0,
                'role_items' => 0,
                'role_tasks' => 0,
                'role_tasks_scope' => 'global',
                'role_projects' => 0,
                'role_projects_scope' => 'global',
                'role_projects_billing' => '0',
                'role_leads' => 0,
                'role_leads_scope' => 'global',
                'role_expenses' => 0,
                'role_expenses_scope' => 'global',
                'role_timesheets' => 0,
                'role_timesheets_scope' => 'global',
                'role_team' => 0,
                'role_team_scope' => 'global',
                'role_tickets' => 0,
                'role_knowledgebase' => 0,
                'role_manage_knowledgebase_categories' => 'no',
                'role_assign_projects' => 'no',
                'role_assign_leads' => 'no',
                'role_assign_tasks' => 'no',
                'role_set_project_permissions' => 'no',
                'role_subscriptions' => '0',
                'role_templates_projects' => '1',
                'role_templates_contracts' => '1',
                'role_templates_proposals' => '1',
                'role_content_import' => 'no',
                'role_content_export' => 'no',
                'role_module_cs_affiliate' => '3',
                'role_homepage' => 'dashboard',
                'role_messages' => 'no',
                'role_reports' => 'no',
                'role_canned' => 'no',
                'role_canned_scope' => 'global',
                'role_workorders' => 0,
                'role_proforma_invoices' => 0
            ],
        ]);
    }
}
