<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SettingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('settings')->insert([
            [
                'settings_id' => 1,
                'settings_created' => '2024-07-11 09:08:22',
                'settings_updated' => '2024-07-11 09:08:22',
                'settings_type' => 'standalone',
                'settings_saas_tenant_id' => null,
                'settings_saas_status' => null,
                'settings_saas_package_id' => null,
                'settings_saas_onetimelogin_key' => null,
                'settings_saas_onetimelogin_destination' => null,
                'settings_saas_package_limits_clients' => null,
                'settings_saas_package_limits_team' => null,
                'settings_saas_package_limits_projects' => null,
                'settings_saas_notification_uniqueid' => null,
                'settings_saas_notification_body' => null,
                'settings_saas_notification_read' => null,
                'settings_saas_notification_action' => null,
                'settings_saas_notification_action_url' => null,
                'settings_saas_email_server_type' => 'local',
                'settings_saas_email_forwarding_address' => '',
                'settings_saas_email_local_address' => '',
                'settings_installation_date' => '2024-07-11 09:08:22',
                'settings_version' => '1.0',
                'settings_company_name' => '',
                'settings_company_address_line_1' => '',
                'settings_company_state' => '',
                'settings_company_city' => '',
                'settings_company_zipcode' => '',
                'settings_company_country' => 'India',
                'settings_company_telephone' => '',
                'settings_company_customfield_1' => '',
                'settings_company_customfield_2' => '',
                'settings_company_customfield_3' => '',
                'settings_company_customfield_4' => '',
                'settings_clients_registration' => 'enabled',
                'settings_clients_shipping_address' => 'enabled',
                'settings_clients_disable_email_delivery' => 'disabled',
                'settings_clients_app_login' => 'enabled',
                'settings_customfields_display_leads' => 'toggled',
                'settings_customfields_display_clients' => 'toggled',
                'settings_customfields_display_projects' => 'toggled',
                'settings_customfields_display_tasks' => 'toggled',
                'settings_customfields_display_tickets' => 'toggled',
                'settings_email_general_variables' => '{our_company_name}, {todays_date}, {email_signature}, {email_footer}, {dashboard_url}',
                'settings_email_from_address' => '',
                'settings_email_from_name' => '',
                'settings_email_server_type' => 'sendmail',
                'settings_email_smtp_host' => '',
                'settings_email_smtp_port' => '',
                'settings_email_smtp_username' => '',
                'settings_email_smtp_password' => '',
                'settings_email_smtp_encryption' => 'tls',
                'settings_estimates_default_terms_conditions' => '<p>Thank you for your business. We look forward to working with you on this project.</p>',
                'settings_estimates_prefix' => 'EST-',
                'settings_estimates_show_view_status' => 'yes',
                'settings_modules_projects' => 'enabled',
                'settings_modules_tasks' => 'enabled',
                'settings_modules_invoices' => 'enabled',
                'settings_modules_payments' => 'enabled',
                'settings_modules_leads' => 'enabled',
                'settings_modules_knowledgebase' => 'enabled',
                'settings_modules_estimates' => 'enabled',
                'settings_modules_expenses' => 'enabled',
                'settings_modules_notes' => 'enabled',
                'settings_modules_subscriptions' => 'enabled',
                'settings_modules_contracts' => 'enabled',
                'settings_modules_proposals' => 'enabled',
                'settings_modules_tickets' => 'enabled',
                'settings_modules_timetracking' => 'enabled',
                'settings_modules_reminders' => 'enabled',
                'settings_modules_spaces' => 'disabled',
                'settings_modules_messages' => 'enabled',
                'settings_modules_reports' => 'enabled',
                'settings_modules_calendar' => 'enabled',
                'settings_files_max_size_mb' => 5000,
                'settings_knowledgebase_article_ordering' => 'name-asc',
                'settings_knowledgebase_allow_guest_viewing' => 'no',
                'settings_knowledgebase_external_pre_body' => null,
                'settings_knowledgebase_external_post_body' => null,
                'settings_knowledgebase_external_header' => null,
                'settings_system_timezone' => 'Asia/Kolkata',
                'settings_system_date_format' => 'm-d-Y',
                'settings_system_datepicker_format' => 'mm-dd-yyyy',
                'settings_system_default_leftmenu' => 'collapsed',
                'settings_system_default_statspanel' => 'collapsed',
                'settings_system_pagination_limits' => 20,
                'settings_system_kanban_pagination_limits' => 20,
                'settings_system_currency_code' => 'INR',
                'settings_system_currency_symbol' => '₹',
                'settings_system_currency_position' => 'left',
                'settings_system_decimal_separator' => 'fullstop',
                'settings_system_thousand_separator' => 'comma',
                'settings_system_close_modals_body_click' => 'no',
                'settings_system_language_default' => 'english',
                'settings_system_language_allow_users_to_change' => 'yes',
                'settings_system_logo_large_name' => 'logo.png',
                'settings_system_logo_small_name' => 'logo-small.png',
                'settings_system_logo_versioning' => '2024-07-11 09:08:22',
                'settings_system_session_login_popup' => 'enabled',
                'settings_system_javascript_versioning' => '2024-07-11',
                'settings_system_exporting_strip_html' => 'yes',
                'settings_tags_allow_users_create' => 'yes',
                'settings_leads_allow_private' => 'yes',
                'settings_leads_allow_new_sources' => 'yes',
                'settings_leads_kanban_value' => 'show',
                'settings_leads_kanban_date_created' => 'show',
                'settings_leads_kanban_category' => 'hide',
                'settings_leads_kanban_date_contacted' => 'show',
                'settings_leads_kanban_telephone' => 'show',
                'settings_leads_kanban_source' => 'hide',
                'settings_leads_kanban_email' => 'show',
                'settings_leads_kanban_tags' => '',
                'settings_leads_kanban_reminder' => '',
                'settings_tasks_client_visibility' => 'visible',
                'settings_tasks_billable' => 'billable',
                'settings_tasks_kanban_date_created' => 'show',
                'settings_tasks_kanban_date_due' => 'show',
                'settings_tasks_kanban_date_start' => 'hide',
                'settings_tasks_kanban_priority' => 'show',
                'settings_tasks_kanban_milestone' => 'hide',
                'settings_tasks_kanban_client_visibility' => 'hide',
                'settings_tasks_kanban_project_title' => 'show',
                'settings_tasks_kanban_client_name' => 'show',
                'settings_tasks_kanban_tags' => '',
                'settings_tasks_kanban_reminder' => '',
                'settings_tasks_send_overdue_reminder' => 'yes',
                'settings_invoices_prefix' => 'INV-',
                'settings_invoices_recurring_grace_period' => 3,
                'settings_invoices_default_terms_conditions' => '<p>Thank you for your business.</p>',
                'settings_invoices_show_view_status' => 'no',
                'settings_invoices_show_project_on_invoice' => 'no',
                'settings_projects_cover_images' => 'enabled',
                'settings_projects_permissions_basis' => 'user_roles',
                'settings_projects_categories_main_menu' => 'no',
                'settings_projects_default_hourly_rate' => null,
                'settings_projects_allow_setting_permission_on_project_creation' => 'yes',
                'settings_projects_clientperm_files_view' => 'yes',
                'settings_projects_clientperm_files_upload' => 'yes',
                'settings_projects_clientperm_comments_view' => 'yes',
                'settings_projects_clientperm_comments_post' => 'yes',
                'settings_projects_clientperm_tasks_view' => 'yes',
                'settings_projects_clientperm_tasks_collaborate' => 'yes',
                'settings_projects_clientperm_tasks_create' => 'yes',
                'settings_projects_clientperm_timesheets_view' => 'yes',
                'settings_projects_clientperm_expenses_view' => 'yes',
                'settings_projects_clientperm_milestones_view' => 'yes',
                'settings_projects_clientperm_assigned_view' => 'no',
                'settings_projects_assignedperm_milestone_manage' => 'yes',
                'settings_projects_assignedperm_tasks_collaborate' => 'yes',
                'settings_projects_events_show_task_status_change' => 'yes',
                'settings_stripe_secret_key' => '',
                'settings_stripe_public_key' => '',
                'settings_stripe_webhooks_key' => '',
                'settings_stripe_default_subscription_plan_id' => NULL,
                'settings_stripe_currency' => 'INR',
                'settings_stripe_display_name' => 'Credit Card',
                'settings_stripe_status' => 'disabled',
                'settings_subscriptions_prefix' => 'SUB-',
                'settings_paypal_email' => '',
                'settings_paypal_currency' => 'INR',
                'settings_paypal_display_name' => 'Paypal',
                'settings_paypal_mode' => 'sandbox',
                'settings_paypal_status' => 'disabled',
                'settings_mollie_live_api_key' => '',
                'settings_mollie_test_api_key' => '',
                'settings_mollie_display_name' => 'Mollie',
                'settings_mollie_mode' => 'sandbox',
                'settings_mollie_currency' => 'INR',
                'settings_mollie_status' => 'disabled',
                'settings_bank_details' => '<p><strong>This is just an example:</strong></p>\r\n<p><strong>Bank Name:</strong>&nbsp;ABCD</p>\r\n<p><strong>Account Name:</strong>&nbsp;ABCD</p>\r\n<p><strong>Account Number:</strong>&nbsp;ABCD</p>',
                'settings_bank_display_name' => 'Bank Transfer',
                'settings_bank_status' => 'enabled',
                'settings_razorpay_keyid' => '',
                'settings_razorpay_secretkey' => '',
                'settings_razorpay_currency' => 'INR',
                'settings_razorpay_display_name' => 'RazorPay',
                'settings_razorpay_status' => 'disabled',
                'settings_completed_check_email' => 'yes',
                'settings_expenses_billable_by_default' => 'yes',
                'settings_tickets_edit_subject' => 'yes',
                'settings_tickets_edit_body' => 'yes',
                'settings_theme_name' => 'default',
                'settings_theme_head' => NULL,
                'settings_theme_body' => NULL,
                'settings_track_thankyou_session_id' => '',
                'settings_proposals_prefix' =>  'PROP-',
                'settings_proposals_show_view_status' => 'yes',
                'settings_contracts_prefix' => 'CO-',
                'settings_contracts_show_view_status' => 'yes',
                'settings_cronjob_has_run' => 'no',
                'settings_cronjob_last_run' =>  NULL,
                'settings_modules_hsnsacs' => 'enabled',
                'settings_company_gst_number' => 'GST',
            ]
        ]);
    }
}
