<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Settings2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('settings2')->insert([
            'settings2_id' => 1,
            'settings2_created' => '2024-07-11 09:08:22',
            'settings2_updated' => '2024-07-11 09:08:22',
            'settings2_bills_pdf_css' => '',
            'settings2_calendar_projects_colour' => '#20AEE3',
            'settings2_calendar_tasks_colour' => '#6772E5',
            'settings2_calendar_events_colour' => '#24D2B5',
            'settings2_calendar_reminder_duration' => 1,
            'settings2_calendar_reminder_period' => 'days',
            'settings2_calendar_events_assigning' => 'admin',
            'settings2_calendar_first_day' => 0,
            'settings2_calendar_default_event_duration' => 30,
            'settings2_calendar_send_reminder_projects' => 'due-date',
            'settings2_calendar_send_reminder_tasks' => 'due-date',
            'settings2_calendar_send_reminder_events' => 'start-date',
            'settings2_captcha_api_site_key' => '',
            'settings2_captcha_api_secret_key' => '',
            'settings2_captcha_status' => 'disabled',
            'settings2_estimates_automation_default_status' => 'disabled',
            'settings2_estimates_automation_create_project' => 'yes',
            'settings2_estimates_automation_project_status' => 'on_hold',
            'settings2_estimates_automation_project_title' => 'New Project',
            'settings2_estimates_automation_project_email_client' => 'yes',
            'settings2_estimates_automation_create_invoice' => 'yes',
            'settings2_estimates_automation_invoice_email_client' => 'yes',
            'settings2_estimates_automation_invoice_due_date' => 7,
            'settings2_estimates_automation_create_tasks' => 'yes',
            'settings2_estimates_automation_copy_attachments' => 'yes',
            'settings2_extras_dimensions_billing' => 'disabled',
            'settings2_extras_dimensions_default_unit' => 'm2',
            'settings2_extras_dimensions_show_measurements' => 'no',
            'settings2_projects_automation_default_status' => 'disabled',
            'settings2_projects_automation_create_invoices' => 'yes',
            'settings2_projects_automation_convert_estimates_to_invoices' => 'yes',
            'settings2_projects_automation_skip_draft_estimates' => 'yes',
            'settings2_projects_automation_skip_declined_estimates' => 'yes',
            'settings2_projects_automation_invoice_unbilled_hours' => 'yes',
            'settings2_projects_automation_invoice_hourly_rate' => NULL,
            'settings2_projects_automation_invoice_hourly_tax_1' => NULL,
            'settings2_projects_automation_invoice_email_client' => 'yes',
            'settings2_projects_automation_invoice_due_date' => '7',
            'settings2_tasks_manage_dependencies' => 'super-users',
            'settings2_tap_secret_key' => '',
            'settings2_tap_publishable_key' => '',
            'settings2_tap_currency_code' => '',
            'settings2_tap_language' => 'en',
            'settings2_tap_display_name' => '',
            'settings2_tap_status' => 'disabled',
            'settings2_paystack_secret_key' => '',
            'settings2_paystack_public_key' => '',
            'settings2_paystack_currency_code' => 'ZAR',
            'settings2_paystack_display_name' => '',
            'settings2_paystack_status' => 'disabled',
            'settings2_proposals_automation_default_status' => 'disabled',
            'settings2_proposals_automation_create_project' => 'no',
            'settings2_proposals_automation_project_status' => 'not_started',
            'settings2_proposals_automation_project_email_client' => 'yes',
            'settings2_proposals_automation_create_invoice' => 'no',
            'settings2_proposals_automation_invoice_email_client' => 'yes',
            'settings2_proposals_automation_invoice_due_date' => 7,
            'settings2_proposals_automation_create_tasks' => 'yes',
            'settings2_file_folders_status' => 'enabled',
            'settings2_file_folders_manage_assigned' => 'yes',
            'settings2_file_folders_manage_project_manager' => 'yes',
            'settings2_file_folders_manage_client' => 'yes',
            'settings2_file_bulk_download' => 'enabled',
            'settings2_search_category_limit' => 5,
            'settings2_spaces_team_space_id' => NULL,
            'settings2_spaces_team_space_status' => 'enabled',
            'settings2_spaces_user_space_status' => 'enabled',
            'settings2_spaces_team_space_title' => 'Team Workspace',
            'settings2_spaces_user_space_title' => 'My Workspace',
            'settings2_spaces_team_space_menu_name' => 'Team Workspace',
            'settings2_spaces_user_space_menu_name' => 'My Workspace',
            'settings2_spaces_features_files' => 'enabled',
            'settings2_spaces_features_notes' => 'enabled',
            'settings2_spaces_features_comments' => 'enabled',
            'settings2_spaces_features_tasks' => 'enabled',
            'settings2_spaces_features_whiteboard' => 'enabled',
            'settings2_spaces_features_checklists' => 'enabled',
            'settings2_spaces_features_todos' => 'enabled',
            'settings2_spaces_features_reminders' => 'enabled',
            'settings2_tickets_replying_interface' => 'inline',
            'settings2_tickets_archive_button' => 'yes',
            'settings2_projects_cover_images_show_on_project' => 'no',
            'settings2_onboarding_status' => 'disabled',
            'settings2_onboarding_content' => '',
            'settings2_onboarding_view_status' => 'seen',
            'settings2_tweak_reports_truncate_long_text' => 'yes',
        ]);
    }
}
