<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'unique_id' => null,
                'created' => '2024-07-11 09:08:22',
                'updated' => '2024-07-11 09:08:22',
                'deleted' => null,
                'creatorid' => 1,
                'email' => 'admin@nscrm.com',
                'password' => Hash::make('123456'),
                'first_name' => 'Neosao',
                'last_name' => 'Services',
                'phone' => null,
                'position' => null,
                'clientid' => null,
                'account_owner' => 'no',
                'primary_admin' => 'yes',
                'avatar_directory' => null,
                'avatar_filename' => null,
                'type' => 'team',
                'status' => 'active',
                'role_id' => 1,
                'last_seen' => '2024-07-11 09:08:22',
                'theme' => 'default',
                'last_ip_address' => null,
                'social_facebook' => null,
                'social_twitter' => null,
                'social_linkedin' => null,
                'social_github' => null,
                'social_dribble' => null,
                'pref_language' => 'english',
                'pref_email_notifications' => 'yes',
                'pref_leftmenu_position' => 'collapsed',
                'pref_statspanel_position' => 'collapsed',
                'pref_filter_own_tasks' => 'no',
                'pref_hide_completed_tasks' => 'no',
                'pref_filter_own_projects' => 'no',
                'pref_filter_show_archived_projects' => 'no',
                'pref_filter_show_archived_tasks' => 'no',
                'pref_filter_show_archived_leads' => 'no',
                'pref_filter_show_archived_tickets' => 'no',
                'pref_filter_own_leads' => 'no',
                'pref_view_tasks_layout' => 'kanban',
                'pref_view_leads_layout' => 'kanban',
                'pref_view_projects_layout' => 'list',
                'pref_theme' => 'default',
                'pref_calendar_dates_projects' => 'due',
                'pref_calendar_dates_tasks' => 'due',
                'pref_calendar_dates_events' => 'due',
                'pref_calendar_view' => 'all',
                'remember_token' => null,
                'remember_filters_tickets_status' => 'disabled',
                'remember_filters_tickets_payload' => null,
                'remember_filters_projects_status' => 'disabled',
                'remember_filters_projects_payload' => null,
                'remember_filters_invoices_status' => 'disabled',
                'remember_filters_invoices_payload' => null,
                'remember_filters_estimates_status' => 'disabled',
                'remember_filters_estimates_payload' => null,
                'remember_filters_contracts_status' => 'disabled',
                'remember_filters_contracts_payload' => null,
                'remember_filters_payments_status' => 'disabled',
                'remember_filters_payments_payload' => null,
                'remember_filters_proposals_status' => 'disabled',
                'remember_filters_proposals_payload' => null,
                'remember_filters_clients_status' => 'disabled',
                'remember_filters_clients_payload' => null,
                'remember_filters_leads_status' => 'disabled',
                'remember_filters_leads_payload' => null,
                'remember_filters_tasks_status' => 'disabled',
                'remember_filters_tasks_payload' => null,
                'remember_filters_subscriptions_status' => 'disabled',
                'remember_filters_subscriptions_payload' => null,
                'remember_filters_products_status' => 'disabled',
                'remember_filters_products_payload' => null,
                'remember_filters_expenses_status' => 'disabled',
                'remember_filters_expenses_payload' => null,
                'remember_filters_timesheets_status' => 'disabled',
                'remember_filters_timesheets_payload' => null,
                'forgot_password_token' => null,
                'forgot_password_token_expiry' => null,
                'force_password_change' => 'no',
                'notifications_system' => 'yes_email',
                'notifications_new_project' => 'no',
                'notifications_projects_activity' => 'yes_email',
                'notifications_billing_activity' => 'yes_email',
                'notifications_new_assignement' => 'yes_email',
                'notifications_leads_activity' => 'yes_email',
                'notifications_tasks_activity' => 'yes_email',
                'notifications_tickets_activity' => 'yes_email',
                'notifications_reminders' => 'yes_email',
                'thridparty_stripe_customer_id' => null,
                'dashboard_access' => 'yes',
                'welcome_email_sent' => 'no',
                'space_uniqueid' => null,
                'timezone' => null,
            ],
        ]);
    }
}
