<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('updating', function (Blueprint $table) {
            $table->id('updating_id');
            $table->dateTime('updating_created');
            $table->dateTime('updating_updated');
            $table->string('updating_type', 100)->comment('modal|cronjob|url');
            $table->string('updating_name', 100)->nullable()->comment('used for updating the record');
            $table->string('updating_function_name', 150)->nullable()->comment('[required] for cronjob updating. This is the name of the function');
            $table->string('updating_update_version', 10)->nullable()->comment('which version this update is for');
            $table->string('updating_request_path', 250)->nullable()->comment('e.g. /updating/action/update-currency-settings');
            $table->string('updating_update_path', 250)->nullable()->comment('e.g. /updating/action/update-currency-settings');
            $table->tinyText('updating_notes')->nullable();
            $table->text('updating_payload_1')->nullable();
            $table->text('updating_payload_2')->nullable();
            $table->text('updating_payload_3')->nullable();
            $table->dateTime('updating_started_date')->nullable();
            $table->dateTime('updating_completed_date')->nullable();
            $table->text('updating_system_log')->nullable()->comment('any comments generated by the system when running this update');
            $table->string('updating_status', 50)->default('new')->comment('new|processing|failed|completed');

            // Adding table comments if needed
            $table->comment = 'Table to track updates and their statuses';
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('updating');
    }
};
